In [1]:
from __future__ import print_function
%load_ext cython
import Cython
print(Cython.__version__)


0.28.2


In [96]:
import numpy as np
np.random.seed(1)
array_1 = np.random.randn(3000,2000).astype(np.float32)
array_2 = np.random.randn(3000,2000).astype(np.float32)
a = 4
b = 3
c = 9


In [97]:
def compute_np(array_1, array_2, a, b, c):
    return np.clip(array_1, 2, 10) * a + array_2 * b + c

In [98]:
timeit_result = %timeit -o compute_np(array_1, array_2, a, b, c)
np_time = timeit_result.average

30.1 ms ± 1.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [109]:
np_result = compute_np(array_1, array_2, a, b, c)


In [94]:
def clip(a, min_value, max_value):
    return min(max(a, min_value), max_value)


def compute(array_1, array_2, a, b, c):
    """
    This function must implement the formula
    np.clip(array_1, 2, 10) * a + array_2 * b + c

    array_1 and array_2 are 2D.
    """
    x_max = array_1.shape[0]
    y_max = array_1.shape[1]
    
    assert array_1.shape == array_2.shape

    result = np.zeros((x_max, y_max), dtype=array_1.dtype)

    for x in range(x_max):
        for y in range(y_max):

            tmp = clip(array_1[x, y], 2, 10)
            tmp = tmp * a + array_2[x, y] * b
            result[x, y] = tmp + c
    
    return result

In [103]:

assert np.all(compute(array_1, array_2, a, b, c) == np_result)


[[15.388825 19.288296 20.030931 ... 19.419691 16.900574 17.979883]
 [14.932588 16.05082   9.772688 ... 15.729271 13.493058 24.789352]
 [15.75753  17.503992 14.187718 ... 19.215025 20.00595  14.38182 ]
 ...
 [17.871357 17.365791 15.70263  ... 20.463781 10.073907 19.816854]
 [13.734241 17.022808 15.42708  ... 16.898031 16.28005  18.229649]
 [15.491308 16.834757 18.519903 ... 16.555904 14.768914 17.483625]]
[[15.388825 19.288296 20.030931 ... 19.419691 16.900574 17.979883]
 [14.932588 16.05082   9.772688 ... 15.729271 13.493058 24.789352]
 [15.75753  17.503992 14.187718 ... 19.215025 20.00595  14.38182 ]
 ...
 [17.871357 17.365791 15.70263  ... 20.463781 10.073907 19.816854]
 [13.734241 17.022808 15.42708  ... 16.898031 16.28005  18.229649]
 [15.491308 16.834757 18.519903 ... 16.555904 14.768914 17.483625]]


AssertionError: 

In [114]:
array_1.shape[0]

3000

In [108]:
r

array([[15.388825, 19.288296, 20.030931, ..., 19.419691, 16.900574,
        17.979883],
       [14.932588, 16.05082 ,  9.772688, ..., 15.729271, 13.493058,
        24.789352],
       [15.75753 , 17.503992, 14.187718, ..., 19.215025, 20.00595 ,
        14.38182 ],
       ...,
       [17.871357, 17.365791, 15.70263 , ..., 20.463781, 10.073907,
        19.816854],
       [13.734241, 17.022808, 15.42708 , ..., 16.898031, 16.28005 ,
        18.229649],
       [15.491308, 16.834757, 18.519903, ..., 16.555904, 14.768914,
        17.483625]], dtype=float32)

In [124]:
test = np.random.randn(2,4)
print(test)
min(test[1,1],2)

[[-0.17496636  0.30620472  1.20399598  1.82854834]
 [-0.07181102 -0.31139834  0.11186169  0.31329316]]


-0.31139833763069086