In [40]:
import numpy as np
N = 1e6
n = 40
A = np.random.randn(n,n)
C = np.dot(A.T, A)

In [41]:
A.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [42]:
A.T.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [43]:
from time import time
AT_F = np.array(np.random.randn(n,n),order='F')
AT_C = np.array(np.random.randn(n,n),order='C')


In [57]:
%time np.dot(A.T, A)
%time A@ A.T

%time np.dot(AT_F, A)
%time np.dot(AT_C, A.T)

CPU times: user 811 µs, sys: 1.36 ms, total: 2.17 ms
Wall time: 2.36 ms
CPU times: user 660 µs, sys: 162 µs, total: 822 µs
Wall time: 781 µs
CPU times: user 536 µs, sys: 216 µs, total: 752 µs
Wall time: 1.51 ms
CPU times: user 368 µs, sys: 130 µs, total: 498 µs
Wall time: 427 µs


array([[ -8.22869157,  11.27262859,   0.24206755, ..., -11.54807832,
          6.96934389,   5.54260427],
       [ -9.92042437,  -5.72179379, -10.10298054, ...,   1.19648235,
         -1.36735648,   6.99188994],
       [ -0.91886647,   0.04831132,  -3.31956027, ...,  -4.04593206,
         -9.88754123,  -4.46946425],
       ...,
       [ -2.43604624,  11.39725987,  -8.56433756, ...,  -1.21626863,
          2.85001116,   1.97001812],
       [ -1.96816695,   0.59112661,  -0.51620287, ...,   4.67942778,
          1.87095233,  -6.45733394],
       [ 12.62866993, -10.76655666,   2.43578916, ...,  -5.1814674 ,
          9.15036178,   8.46101459]])

In [56]:
A.T

array([[ 0.04531198,  1.03726904, -2.30080393, ...,  1.39022379,
         1.22285488, -0.77571747],
       [-0.54435015,  1.89928138,  1.56046511, ..., -1.2819292 ,
         0.77413631, -0.64017807],
       [ 1.13579921, -0.45885191,  1.97893708, ..., -0.12545222,
         1.6471072 , -0.31288894],
       ...,
       [-0.84661461, -1.14877718,  1.15345137, ...,  1.01223024,
        -1.24750976, -0.06232631],
       [ 0.69571234,  0.85863985, -0.27963026, ...,  0.15437208,
         1.67514493,  0.56194878],
       [ 1.01206478,  0.29086414, -0.72284045, ...,  0.09351096,
        -0.09028194,  0.93185274]])

In [55]:
AT_C

array([[-1.17636114,  0.81000011, -1.23709351, ..., -2.57843465,
         0.22890735,  1.36284318],
       [-0.97362352, -0.91802253, -1.06652961, ..., -0.99397714,
         0.45355914,  0.30296141],
       [-0.03071952,  0.45461889, -0.83881325, ...,  0.33470805,
        -1.23843954, -1.3749755 ],
       ...,
       [-0.83105157,  2.11490963, -0.62997523, ...,  0.56143211,
        -1.30564124,  0.38036011],
       [ 0.74046596,  0.20824569, -0.09325411, ..., -1.46077885,
        -0.72572756,  1.60208435],
       [ 1.10755791, -0.27959009, -1.7386363 , ...,  0.46082754,
         0.83497201,  0.5965526 ]])